export const ERROR_COMMAND_NOT_FOUND = 'ERROR_COMMAND_NOT_FOUND';
export const ERROR_COMMAND_BAD_REQUEST = 'ERROR_COMMAND_BAD_REQUEST';

export const ERROR_COMMAND_ADD_EVENT_EMITTER_BAD_REQUEST =
  'ERROR_COMMAND_ADD_EVENT_EMITTER_BAD_REQUEST';
